/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author alumnos
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    private ImageIcon imagen;
    private Icon icono;
    public frmPrincipal() {
        initComponents();
        this.setTitle("Hospital UTE");
        this.setLocationRelativeTo(frmPrincipal.this);
        this.setResizable(false);
        this.pintarImagen(this.lblminimizar,"src/hospital/Imagenes/mini.png");
        this.pintarImagen(this.lblcerrar,"src/hospital/Imagenes/cerrar.png");
        this.pintarImagen(this.lblPortada,"src/hospital/Imagenes/portadaHospi.jpg");
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPortada = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        btnGestionarPacientes = new javax.swing.JButton();
        btnGestionarCitas = new javax.swing.JButton();
        btnGestionarVentas = new javax.swing.JButton();
        btnGestionarEmpleados = new javax.swing.JButton();
        btnGestionarMedicamentos = new javax.swing.JButton();
        btnGestionarHorarios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblcerrar = new javax.swing.JLabel();
        lblminimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOSPITAL...");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(" Hospital UTE");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        lblPortada.setBorder(new javax.swing.border.MatteBorder(null));
        bg.add(lblPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 510, 240));

        panel.setBackground(new java.awt.Color(54, 33, 89));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionarPacientes.setBackground(new java.awt.Color(85, 55, 118));
        btnGestionarPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarPacientes.setText("Gestionar Pacientes");
        btnGestionarPacientes.setBorder(null);
        btnGestionarPacientes.setBorderPainted(false);
        btnGestionarPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionarPacientes.setPreferredSize(new java.awt.Dimension(162, 22));
        btnGestionarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPacientesActionPerformed(evt);
            }
        });
        panel.add(btnGestionarPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 39));

        btnGestionarCitas.setBackground(new java.awt.Color(85, 55, 118));
        btnGestionarCitas.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarCitas.setText("Gestionar Citas");
        btnGestionarCitas.setBorder(null);
        btnGestionarCitas.setPreferredSize(new java.awt.Dimension(162, 22));
        panel.add(btnGestionarCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 190, 38));

        btnGestionarVentas.setBackground(new java.awt.Color(85, 55, 118));
        btnGestionarVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarVentas.setText("Gestionar Ventas");
        btnGestionarVentas.setBorder(null);
        btnGestionarVentas.setPreferredSize(new java.awt.Dimension(162, 22));
        panel.add(btnGestionarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 41));

        btnGestionarEmpleados.setBackground(new java.awt.Color(85, 55, 118));
        btnGestionarEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarEmpleados.setText("Gestionar Empleados");
        btnGestionarEmpleados.setBorder(null);
        btnGestionarEmpleados.setPreferredSize(new java.awt.Dimension(162, 22));
        panel.add(btnGestionarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 190, 38));

        btnGestionarMedicamentos.setBackground(new java.awt.Color(85, 55, 118));
        btnGestionarMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarMedicamentos.setText("Gestionar Medicamentos");
        btnGestionarMedicamentos.setBorder(null);
        btnGestionarMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarMedicamentosActionPerformed(evt);
            }
        });
        panel.add(btnGestionarMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 190, 39));

        btnGestionarHorarios.setBackground(new java.awt.Color(85, 55, 118));
        btnGestionarHorarios.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarHorarios.setText("Gestionar Horarios");
        btnGestionarHorarios.setBorder(null);
        btnGestionarHorarios.setPreferredSize(new java.awt.Dimension(162, 22));
        panel.add(btnGestionarHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 190, 38));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/símbolo-de-la-medicina-fondo-abstracto-15695345.jpg"))); // NOI18N
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 110));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Servicios");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 77, 30));

        bg.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 510));

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        lblcerrar.setBorder(new javax.swing.border.MatteBorder(null));
        lblcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcerrarMouseClicked(evt);
            }
        });

        lblminimizar.setBorder(new javax.swing.border.MatteBorder(null));
        lblminimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 720, Short.MAX_VALUE)
                .addComponent(lblminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizarMouseClicked
        // TODO add your handling code here:
        this.setState(frmPrincipal.ICONIFIED);
    }//GEN-LAST:event_lblminimizarMouseClicked

    private void lblcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcerrarMouseClicked
        // TODO add your handling code here:
        int dialog = JOptionPane.YES_NO_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea salir", "Exist", dialog);
        if (result == 0) {
             System.exit(0);//cierra la ventana
        }
       
    }//GEN-LAST:event_lblcerrarMouseClicked

    private void btnGestionarMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarMedicamentosActionPerformed
        // TODO add your handling code here:
        new frmMedicamento().setVisible(true);
 

        clasesHospital.Medicamentos cm = new clasesHospital.Medicamentos(); //instanciar paquete claseHospital
        cm.crearArchivoMedicamentos();
        //cm.guardarMedicamento();
    }//GEN-LAST:event_btnGestionarMedicamentosActionPerformed

    private void btnGestionarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarPacientesActionPerformed
 
    int xx;
    int xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
     private void pintarImagen(JLabel lbl, String ruta) {
         this.imagen = new ImageIcon(ruta);
         this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                 lbl.getWidth(), 
                 lbl.getHeight(),
                 Image.SCALE_DEFAULT)
         );
         lbl.setIcon(this.icono);//convierte imagen en icono
         this.repaint();
     }//Todo -- pintarImagen

    @Override
    public boolean isDisplayable() {
        return super.isDisplayable(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnGestionarCitas;
    private javax.swing.JButton btnGestionarEmpleados;
    private javax.swing.JButton btnGestionarHorarios;
    private javax.swing.JButton btnGestionarMedicamentos;
    private javax.swing.JButton btnGestionarPacientes;
    private javax.swing.JButton btnGestionarVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JLabel lblcerrar;
    private javax.swing.JLabel lblminimizar;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
