/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hospital;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;


/**
 *
 * @author Usuario
 */
public class pnlCitas extends javax.swing.JPanel {

    /**
     * Creates new form pnlPacientes
     */
    public pnlCitas() {
        initComponents();
        btnGuardar.setEnabled(false);
        jcbDepartamento.setEnabled(false);
        jcbSexo.setEnabled(false);
        jdcFechaCita.setEnabled(false);
        
       
    }
    public void habilitarBoton() {
        if (!txtCedula.getText().isEmpty()
              && !txtEdad.getText().isEmpty()  
              && !txtDireccion.getText().isEmpty()
              && !txtEspecialidad.getText().isEmpty()
              && !txtEspecialidad.getText().isEmpty()
              && !txtDescripcion.getText().isEmpty()
              && !txtHora.getText().isEmpty()) {
            jcbDepartamento.setEnabled(true);
            jcbSexo.setEnabled(true);
             jdcFechaCita.setEnabled(true);
            btnGuardar.setEnabled(true);
        }else {
            jcbDepartamento.setEnabled(false);
            jcbSexo.setEnabled(false);
            jdcFechaCita.setEnabled(false);
            btnGuardar.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCitas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jblFechaCita = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnMostrarCita = new javax.swing.JButton();
        btnSeleccionarCitas = new javax.swing.JButton();
        btnEliminarCita = new javax.swing.JButton();
        btnEditarCita = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jblFechaCita1 = new javax.swing.JLabel();
        jblFechaCita2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jblFechaCita3 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jcbDepartamento = new javax.swing.JComboBox<>();
        jblFechaCita4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jdcFechaCita = new com.toedter.calendar.JDateChooser();
        jcbSexo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCitas.setBackground(new java.awt.Color(0, 255, 153));
        panelCitas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombres:");
        panelCitas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dirección:");
        panelCitas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Edad:");
        panelCitas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, -1));

        jblFechaCita.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblFechaCita.setForeground(new java.awt.Color(0, 0, 0));
        jblFechaCita.setText("Hora:");
        panelCitas.add(jblFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 50, 20));

        txtEdad.setBackground(new java.awt.Color(255, 255, 255));
        txtEdad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEdad.setBorder(null);
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEdadKeyReleased(evt);
            }
        });
        panelCitas.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, 20));

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDireccion.setBorder(null);
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionKeyReleased(evt);
            }
        });
        panelCitas.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 160, 20));

        txtEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        txtEspecialidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecialidad.setBorder(null);
        txtEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadActionPerformed(evt);
            }
        });
        txtEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEspecialidadKeyReleased(evt);
            }
        });
        panelCitas.add(txtEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, 20));

        txtCedula.setBackground(new java.awt.Color(255, 255, 255));
        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCedula.setBorder(null);
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        panelCitas.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cedula:");
        panelCitas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));
        panelCitas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 160, 10));
        panelCitas.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, 10));
        panelCitas.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 160, 10));
        panelCitas.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 150, 10));

        btnGuardar.setBackground(new java.awt.Color(0, 204, 153));
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelCitas.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, -1));

        btnMostrarCita.setBackground(new java.awt.Color(0, 204, 153));
        btnMostrarCita.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarCita.setText("Mostrar");
        btnMostrarCita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCitaActionPerformed(evt);
            }
        });
        panelCitas.add(btnMostrarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 50, 20));

        btnSeleccionarCitas.setBackground(new java.awt.Color(0, 204, 153));
        btnSeleccionarCitas.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionarCitas.setText("Seleccionar");
        btnSeleccionarCitas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeleccionarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarCitasActionPerformed(evt);
            }
        });
        panelCitas.add(btnSeleccionarCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 80, -1));

        btnEliminarCita.setBackground(new java.awt.Color(0, 204, 153));
        btnEliminarCita.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarCita.setText("Eliminar");
        btnEliminarCita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCitaActionPerformed(evt);
            }
        });
        panelCitas.add(btnEliminarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 60, -1));

        btnEditarCita.setBackground(new java.awt.Color(0, 204, 153));
        btnEditarCita.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarCita.setText("Editar");
        btnEditarCita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCitaActionPerformed(evt);
            }
        });
        panelCitas.add(btnEditarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Sexo:");
        panelCitas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, 20));

        jblFechaCita1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblFechaCita1.setForeground(new java.awt.Color(0, 0, 0));
        jblFechaCita1.setText("Fecha de cita:");
        panelCitas.add(jblFechaCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 20));

        jblFechaCita2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jblFechaCita2.setForeground(new java.awt.Color(0, 0, 0));
        jblFechaCita2.setText("Departamento:");
        panelCitas.add(jblFechaCita2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 20));

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefono.setBorder(null);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        panelCitas.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 160, 20));
        panelCitas.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 160, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Teléfono:");
        panelCitas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 80, -1));

        txtNombres.setBackground(new java.awt.Color(255, 255, 255));
        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombres.setBorder(null);
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
        });
        panelCitas.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 160, 20));
        panelCitas.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 160, 10));
        panelCitas.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 630, -1));

        jblFechaCita3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblFechaCita3.setForeground(new java.awt.Color(0, 0, 0));
        jblFechaCita3.setText("Especialidad:");
        panelCitas.add(jblFechaCita3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 20));

        txtHora.setBackground(new java.awt.Color(255, 255, 255));
        txtHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHora.setBorder(null);
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHoraKeyReleased(evt);
            }
        });
        panelCitas.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 150, 20));
        panelCitas.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, 10));

        jcbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Neurología", "Cardiología", "Ortopedía", "Oftalmología", "Oncología", "Psquiatría", "Reumatología", "Medicina General" }));
        jcbDepartamento.setToolTipText("");
        panelCitas.add(jcbDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 150, -1));

        jblFechaCita4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblFechaCita4.setForeground(new java.awt.Color(0, 0, 0));
        jblFechaCita4.setText("Descripción:");
        panelCitas.add(jblFechaCita4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 100, 20));

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescripcion.setBorder(new javax.swing.border.MatteBorder(null));
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
        });
        panelCitas.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 150, 60));

        jdcFechaCita.setBackground(new java.awt.Color(153, 0, 153));
        panelCitas.add(jdcFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 150, -1));

        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masculino", "femenino", " " }));
        panelCitas.add(jcbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 160, -1));

        add(panelCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 530, 250));

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombres", "Edad", "Dirección", "Teléfono", "Sexo", "Especialidad", "Fecha cita", "Departamento", "Descripción", "Hora"
            }
        ));
        tblCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCitas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 620, 170));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestionar Citas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/fc.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 650, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionKeyReleased

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtHoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraKeyReleased

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresKeyReleased

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnEditarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCitaActionPerformed
        // TODO add your handling code here:
        clasesHospital.Pacientes cp=new clasesHospital.Pacientes();
        cp.editarPaciente(tblCitas);
    }//GEN-LAST:event_btnEditarCitaActionPerformed

    private void btnEliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCitaActionPerformed
        // TODO add your handling code here:
        boolean validar = validarCampos();
        if(validar == true){
            clasesHospital.Pacientes cp=new clasesHospital.Pacientes();
            cp.eliminarPaciente(tblCitas, txtCedula);
            limpiarCampos();
        }
    }//GEN-LAST:event_btnEliminarCitaActionPerformed

    private void btnSeleccionarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarCitasActionPerformed
        // TODO add your handling code here:
        clasesHospital.Citas cc=new clasesHospital.Citas();
        cc.seleccionarCita(tblCitas);
        txtCedula.setText(cc.getCedula());
        txtNombres.setText(cc.getNombres());
        txtEdad.setText(cc.getNombres());
        txtDireccion.setText(cc.getDireccion());
        txtTelefono.setText(cc.getTelefono());
        txtEspecialidad.setText(cc.getTelefono());
        txtDescripcion.setText(cc.getCedula());
        txtHora.setText(cc.getHora());
        jcbDepartamento.setSelectedItem(cc.getDepartamento());
        
        
        jcbSexo.setSelectedItem(cc.getSexo());
    }//GEN-LAST:event_btnSeleccionarCitasActionPerformed

    private void btnMostrarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCitaActionPerformed
        // TODO add your handling code here:
        clasesHospital.Citas cc=new clasesHospital.Citas();
        cc.mostrarCitas(tblCitas);
    }//GEN-LAST:event_btnMostrarCitaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String fecha;
        boolean validar = validarCampos();
        SimpleDateFormat f = new SimpleDateFormat("yyyy/MM/dd");
        //pociciono en la variable
        fecha = f.format(jdcFechaCita.getDate());
        if(validar == true){
            clasesHospital.Citas cc = new clasesHospital.Citas();
            cc.setCedula(txtCedula.getText());
            cc.setNombres(txtNombres.getText());
            cc.setEdad(txtEdad.getText());
            cc.setDireccion(txtDireccion.getText());
            cc.setTelefono(txtTelefono.getText());
            cc.setSexo(jcbSexo.getSelectedItem().toString());
            cc.setEspecialidad(txtEspecialidad.getText());
            cc.setFechaCita(fecha);
            cc.setDepartamento(jcbDepartamento.getSelectedItem().toString());
            cc.setDescripcion(txtDescripcion.getText());
            cc.setHora(txtHora.getText());
            cc.guardarCitas();
            limpiarCampos();
            btnGuardar.setEnabled(false);
            cc.mostrarCitas(tblCitas);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        //se activa cuando se escribe
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtEspecialidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspecialidadKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtEspecialidadKeyReleased

    private void txtEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadActionPerformed

    private void txtDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtDireccionKeyReleased

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtEdadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtEdadKeyReleased

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void tblCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCitasMouseClicked
        // TODO add your handling code here:
        //modificar fecha
        String is_fecha = String.valueOf(tblCitas.getValueAt(tblCitas.getSelectedRow(),7));
        SimpleDateFormat sf = new SimpleDateFormat("yyyy/MM/dd");
        Date fecha;
        try {
            fecha = (Date)sf.parse(is_fecha);
            jdcFechaCita.setDate(fecha);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_tblCitasMouseClicked

     private void limpiarCampos() {
        txtCedula.setText("");
        txtNombres.setText("");
        txtEdad.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtEspecialidad.setText("");
        txtDescripcion.setText("");
        txtHora.setText("");
        
    }//TODO -- limpiarCampos
     private boolean validarCampos() {
        if (txtCedula.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo cedula");
            return false;
        }else if(txtNombres.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo nombre");
            return false;
        }else if(txtEdad.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo edad");
            return false;
        }else if(txtDireccion.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo direccion");
            return false;
        }else if(txtTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo telefono");
            return false;
        }else if(txtEspecialidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo especialidad");
            return false; 
        }else if(txtDescripcion.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo descripcion");
            return false;
        }else if(txtHora.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo hora");
            return false;
        }
        return  true;
    }//TODO -- validarCampos

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCita;
    private javax.swing.JButton btnEliminarCita;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarCita;
    private javax.swing.JButton btnSeleccionarCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jblFechaCita;
    private javax.swing.JLabel jblFechaCita1;
    private javax.swing.JLabel jblFechaCita2;
    private javax.swing.JLabel jblFechaCita3;
    private javax.swing.JLabel jblFechaCita4;
    private javax.swing.JComboBox<String> jcbDepartamento;
    private javax.swing.JComboBox<String> jcbSexo;
    private com.toedter.calendar.JDateChooser jdcFechaCita;
    private javax.swing.JPanel panelCitas;
    private javax.swing.JTable tblCitas;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
