/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hospital;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class pnlEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form pnlPacientes
     */
    public pnlEmpleados() {
        initComponents();
        jcbxPuesto.setEnabled(false);
        jcbArea.setEnabled(false);
        jckMatutino.setEnabled(false);
        jckVespertino.setEnabled(false); 
        jckNocturno.setEnabled(false);
        btnGuardar.setEnabled(false);
    }
    public void habilitarBoton() {
        if (!txtCedula.getText().isEmpty()
              && !txtNombres.getText().isEmpty()  
              && !txtDireccion.getText().isEmpty()
              && !txtTelefono.getText().isEmpty()
              && !txtEdad.getText().isEmpty()
              && !txtIngreso.getText().isEmpty()
              && !txtSalida.getText().isEmpty()
              ) {
            jcbxPuesto.setEnabled(true);
            jcbArea.setEnabled(true);
            jckMatutino.setEnabled(true);
            jckVespertino.setEnabled(true);
            jckNocturno.setEnabled(true);
            btnGuardar.setEnabled(true);
        }else {
            jcbxPuesto.setEnabled(false);
            jcbxPuesto.setSelectedIndex(0);
            jcbArea.setEnabled(false);
            jcbArea.setSelectedIndex(0);
            jckMatutino.setEnabled(false);
            jckMatutino.setSelected(false);
            jckVespertino.setEnabled(false);
            jckVespertino.setSelected(false);
            jckNocturno.setEnabled(false);
            jckNocturno.setSelected(false);
            btnGuardar.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngJornada = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtSalida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnMostrarEmpleados = new javax.swing.JButton();
        btnSeleccionarEmpleados = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jckMatutino = new javax.swing.JCheckBox();
        jckVespertino = new javax.swing.JCheckBox();
        jcbArea = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jcbxPuesto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jckNocturno = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtIngreso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jlbPanelx = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombres:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dirección:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hora salida");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 100, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jornada");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, 20));

        txtNombres.setBackground(new java.awt.Color(204, 255, 204));
        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombres.setBorder(null);
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
        });
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 160, 20));

        txtDireccion.setBackground(new java.awt.Color(204, 255, 204));
        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDireccion.setBorder(null);
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionKeyReleased(evt);
            }
        });
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 160, 20));

        txtTelefono.setBackground(new java.awt.Color(204, 255, 204));
        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTelefono.setBorder(null);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 160, 20));

        txtSalida.setBackground(new java.awt.Color(204, 255, 204));
        txtSalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSalida.setBorder(null);
        txtSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalidaActionPerformed(evt);
            }
        });
        txtSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSalidaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalidaKeyTyped(evt);
            }
        });
        jPanel2.add(txtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 100, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Puesto:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 204, 153));
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, -1));

        btnMostrarEmpleados.setBackground(new java.awt.Color(0, 204, 153));
        btnMostrarEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarEmpleados.setText("Mostrar");
        btnMostrarEmpleados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarEmpleadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnMostrarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 50, 20));

        btnSeleccionarEmpleados.setBackground(new java.awt.Color(0, 204, 153));
        btnSeleccionarEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionarEmpleados.setText("Seleccionar");
        btnSeleccionarEmpleados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeleccionarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarEmpleadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeleccionarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 80, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 204, 153));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 60, -1));

        btnEditar.setBackground(new java.awt.Color(0, 204, 153));
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 60, -1));

        btngJornada.add(jckMatutino);
        jckMatutino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jckMatutino.setForeground(new java.awt.Color(0, 0, 0));
        jckMatutino.setText("Matutino");
        jckMatutino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckMatutinoActionPerformed(evt);
            }
        });
        jPanel2.add(jckMatutino, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        btngJornada.add(jckVespertino);
        jckVespertino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jckVespertino.setForeground(new java.awt.Color(0, 0, 0));
        jckVespertino.setText("Vespertino");
        jPanel2.add(jckVespertino, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jcbArea.setBackground(new java.awt.Color(204, 255, 204));
        jcbArea.setForeground(new java.awt.Color(0, 0, 0));
        jcbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Anestesiología", "Cirugía general y digestiva", "Laboratorios clínicos", "Cardiología", "Cirugía ortopédica y traumatología", "Radiodiagnóstico", "Cuidados intensivos", "Dermatología", "Farmacia", "Digestivo", "Ginecología y obstetricia", "Medicina preventiva", "Hematología", "Oftalmología", "Medicina interna", "Otorrinolariongología", "Nefrología", "Urología ", "Neumología ", "Oncología\t ", "Pediatría/neonatología ", "Rehabilitación ", "Urgencias" }));
        jcbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAreaActionPerformed(evt);
            }
        });
        jPanel2.add(jcbArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 130, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cedula:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jcbxPuesto.setBackground(new java.awt.Color(204, 255, 204));
        jcbxPuesto.setForeground(new java.awt.Color(0, 0, 0));
        jcbxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Médicos generales. ", "Radiólogos. ", "Oftalmólogos. ", "Pediatras. ", "Ginecólogo.", "Oncólogo.", "Neurólogo. ", "Cardiólogo. ", "Endocrinólogo. ", "Psiquiatras.  ", "Epidemiólogo.", "Inmunólogo.", "Nutricionista.", "Anestesiólogo. ", "Tecnólogo quirúrgico. ", "Asistente médico.  ", "Educador de salud. ", "Kinesiologo.", "Quiroprácticos.", "Farmacéutico. ", "Dentistas.", "Técnicos dentales.", "Enfermeras dentales. ", "Terapeutas dentales. ", "Patología del habla y lenguaje.", "Técnico psiquiátrico. ", "Terapeuta recreativo. ", "Terapeuta ocupacional. ", "Terapeuta respiratoria.", "Cuidado agudo.", "Quirófano.", "Maternidad.", "Medicina laboral.", "Servicios de atención ambulatoria. ", "Servicios de emergencia.", "Servicios geriátricos. ", "Servicios de salud comunitaria. ", "Gerente de recursos humanos y ejecutivos.", "Cajero.", "Recepcionista.", "Secretaria.", "Contador.", "Gestores administrativos de servicio. ", "Gerentes operacionales.", "Seguridad" }));
        jcbxPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxPuestoActionPerformed(evt);
            }
        });
        jPanel2.add(jcbxPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 130, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Area:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teléfono:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, -1));

        txtCedula.setBackground(new java.awt.Color(204, 255, 204));
        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCedula.setBorder(null);
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 160, 20));

        btngJornada.add(jckNocturno);
        jckNocturno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jckNocturno.setForeground(new java.awt.Color(0, 0, 0));
        jckNocturno.setText("Nocturno");
        jPanel2.add(jckNocturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hora ingreso");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 110, -1));

        txtIngreso.setBackground(new java.awt.Color(204, 255, 204));
        txtIngreso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIngreso.setBorder(null);
        txtIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresoActionPerformed(evt);
            }
        });
        txtIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIngresoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresoKeyTyped(evt);
            }
        });
        jPanel2.add(txtIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 100, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Edad:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, -1));

        txtEdad.setBackground(new java.awt.Color(204, 255, 204));
        txtEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEdad.setBorder(null);
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEdadKeyReleased(evt);
            }
        });
        jPanel2.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 160, 20));

        jlbPanelx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/gggg.jpg"))); // NOI18N
        jPanel2.add(jlbPanelx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 260));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 260));

        tblEmpleados.setBackground(new java.awt.Color(153, 204, 255));
        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombres", "Dirección", "Teléfono", "Jornada", "Hora ingreso", "Hora salida", "Area", "Puesto"
            }
        ));
        jScrollPane1.setViewportView(tblEmpleados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 650, 210));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestionar Empleados");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtNombresKeyReleased

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtDireccionKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalidaActionPerformed

    private void txtSalidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalidaKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtSalidaKeyReleased

    private void txtSalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalidaKeyTyped
        // TODO add your handling code here:
        //se activa cuando se escribe
    }//GEN-LAST:event_txtSalidaKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        boolean validar = validarCampos();
        if(validar == true){
            clasesHospital.Empleados ce = new clasesHospital.Empleados();
            ce.setCedula(txtCedula.getText());
            ce.setNombres(txtNombres.getText());
            ce.setDireccion(txtDireccion.getText());
            ce.setTelefono(txtTelefono.getText());
            ce.setEdad(txtEdad.getText());
            ce.setJornada(validarSeleccion());
            ce.setIngreso(txtIngreso.getText());
            ce.setSalida(txtSalida.getText());
            ce.setArea(jcbArea.getSelectedItem().toString());
            ce.setPuesto(jcbxPuesto.getSelectedItem().toString());
            ce.guardarEmpleados();
            limpiarCampos();
            
            ce.mostrarEmpleados(tblEmpleados);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
   
    private String validarSeleccion() {
        String seleccion = "";
        if (jckMatutino.isSelected()) {
            seleccion = "Matutino";
            return seleccion;
        }
        if (jckVespertino.isSelected()) {
            seleccion = "Vespertino";
            return seleccion;
        }
        if (jckNocturno.isSelected()) {
            seleccion = "Nocturno";
            return seleccion;
        }
        return seleccion;
    }
     private void limpiarCampos() {
        txtCedula.setText("");
        txtNombres.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtEdad.setText("");
        txtIngreso.setText("");
        txtSalida.setText("");
        btngJornada.clearSelection();
        habilitarBoton();
        
        
    }//TODO -- limpiarCampos
     private boolean validarCampos() {
        if (txtCedula.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo cedula");
            return false;
        }else if(txtNombres.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo nombre");
            return false;
        }else if(txtDireccion.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo direccción");
            return false;
        }else if(txtTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo telefono");
            return false;
        }else if(txtEdad.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo edad");
            return false;
        }else if(txtIngreso.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo ingreso");
            return false;
        }else if(txtSalida.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo salida");
            return false;
        }
        return  true;
    }//TODO -- validarCampos
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        clasesHospital.Empleados ce=new clasesHospital.Empleados();
        ce.editarEmpleado(tblEmpleados);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        boolean validar = validarCampos();
        if(validar == true){
            clasesHospital.Empleados ce=new clasesHospital.Empleados();
            ce.eliminarEmpleados(tblEmpleados, txtCedula);
            limpiarCampos();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSeleccionarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarEmpleadosActionPerformed
        // TODO add your handling code here:
        clasesHospital.Empleados ce=new clasesHospital.Empleados();
        ce.seleccionarEmpleados(tblEmpleados);
        txtCedula.setText(ce.getCedula());
        txtNombres.setText(ce.getNombres());
        txtDireccion.setText(ce.getDireccion());
        txtTelefono.setText(ce.getTelefono());
        txtEdad.setText(ce.getEdad());
        txtIngreso.setText(ce.getIngreso());    
        txtSalida.setText(ce.getSalida());    
        jcbxPuesto.setSelectedItem(ce.getPuesto());
        jcbArea.setSelectedItem(ce.getArea());
        habilitarBoton();
    }//GEN-LAST:event_btnSeleccionarEmpleadosActionPerformed

    private void btnMostrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEmpleadosActionPerformed
        // TODO add your handling code here:
        clasesHospital.Empleados ce=new clasesHospital.Empleados();
        ce.mostrarEmpleados(tblEmpleados);
    }//GEN-LAST:event_btnMostrarEmpleadosActionPerformed

    private void jcbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAreaActionPerformed

    private void jckMatutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckMatutinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jckMatutinoActionPerformed

    private void jcbxPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxPuestoActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresoActionPerformed

    private void txtIngresoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresoKeyReleased

    private void txtIngresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresoKeyTyped

    private void txtEdadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarEmpleados;
    private javax.swing.JButton btnSeleccionarEmpleados;
    private javax.swing.ButtonGroup btngJornada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbArea;
    private javax.swing.JComboBox<String> jcbxPuesto;
    private javax.swing.JCheckBox jckMatutino;
    private javax.swing.JCheckBox jckNocturno;
    private javax.swing.JCheckBox jckVespertino;
    private javax.swing.JLabel jlbPanelx;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIngreso;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtSalida;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
