/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hospital;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class pnlHorarios extends javax.swing.JPanel {

    /**
     * Creates new form pnlPacientes
     */
    
    public pnlHorarios() {
        initComponents();
        btnGuardar.setEnabled(false);
        jcbExtras.setEnabled(false);
    }
    public void habilitarBoton() {
        if (!txtNombres.getText().isEmpty()
              && !txtDepartamento.getText().isEmpty()  
              && !txtEntrada.getText().isEmpty()
              && !txtSalida.getText().isEmpty()
              ) {
            jcbExtras.setEnabled(true);
            btnGuardar.setEnabled(true);
           
        }else {
            jcbExtras.setEnabled(false);
             jcbExtras.setSelectedItem(0);
            btnGuardar.setEnabled(false);
             
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnDatos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        txtEntrada = new javax.swing.JTextField();
        txtSalida = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnMostrarMedicamentos1 = new javax.swing.JButton();
        btnSeleccionarMedicamentos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jcbExtras = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnDatos.setBackground(new java.awt.Color(0, 153, 153));
        jpnDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Departamento:");
        jpnDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora entrada:");
        jpnDatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hora salida:");
        jpnDatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        txtDepartamento.setBackground(new java.awt.Color(204, 255, 204));
        txtDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDepartamento.setBorder(null);
        txtDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartamentoActionPerformed(evt);
            }
        });
        txtDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDepartamentoKeyReleased(evt);
            }
        });
        jpnDatos.add(txtDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 90, 30));

        txtEntrada.setBackground(new java.awt.Color(204, 255, 204));
        txtEntrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEntrada.setBorder(null);
        txtEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaActionPerformed(evt);
            }
        });
        txtEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEntradaKeyReleased(evt);
            }
        });
        jpnDatos.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 90, 30));

        txtSalida.setBackground(new java.awt.Color(204, 255, 204));
        txtSalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSalida.setBorder(null);
        txtSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSalidaKeyReleased(evt);
            }
        });
        jpnDatos.add(txtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 90, 30));

        txtNombres.setBackground(new java.awt.Color(204, 255, 204));
        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombres.setBorder(null);
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        jpnDatos.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres:");
        jpnDatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 204, 153));
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpnDatos.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, -1));

        btnMostrarMedicamentos1.setBackground(new java.awt.Color(0, 204, 153));
        btnMostrarMedicamentos1.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarMedicamentos1.setText("Mostrar");
        btnMostrarMedicamentos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrarMedicamentos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMedicamentos1ActionPerformed(evt);
            }
        });
        jpnDatos.add(btnMostrarMedicamentos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 60, 20));

        btnSeleccionarMedicamentos.setBackground(new java.awt.Color(0, 204, 153));
        btnSeleccionarMedicamentos.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionarMedicamentos.setText("Seleccionar");
        btnSeleccionarMedicamentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeleccionarMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarMedicamentosActionPerformed(evt);
            }
        });
        jpnDatos.add(btnSeleccionarMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 80, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 204, 153));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpnDatos.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, -1));

        btnEditar.setBackground(new java.awt.Color(0, 204, 153));
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jpnDatos.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Horas extras:");
        jpnDatos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jcbExtras.setBackground(new java.awt.Color(204, 255, 204));
        jcbExtras.setForeground(new java.awt.Color(0, 0, 0));
        jcbExtras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jpnDatos.add(jcbExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 90, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/xs.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnDatos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 290));

        add(jpnDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 290));

        tblHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Departamento", "Hora entrada", "Hora salida", "Horas extras"
            }
        ));
        jScrollPane1.setViewportView(tblHorarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 350, 290));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestionar Horarios");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/fondoMedi.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartamentoActionPerformed

    private void txtDepartamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepartamentoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtDepartamentoKeyReleased

    private void txtEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaActionPerformed

    private void txtEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtEntradaKeyReleased

    private void txtSalidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalidaKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtSalidaKeyReleased

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtNombresKeyReleased

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        // TODO add your handling code here:
        //se activa cuando se escribe
    }//GEN-LAST:event_txtNombresKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        boolean validar = validarCampos();
        if(validar == true){
            clasesHospital.Horarios ch = new clasesHospital.Horarios();
            ch.setNombres(txtNombres.getText());
            ch.setDepartamento(txtDepartamento.getText());
            ch.setEntrada(txtEntrada.getText());
            ch.setSalida(txtSalida.getText());
            ch.setExtras(jcbExtras.getSelectedItem().toString());
            ch.guardarHorarios();
            limpiarCampos();
            habilitarBoton();
            ch.mostrarHorarios(tblHorarios);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

     private void limpiarCampos() {
        txtNombres.setText("");
        txtDepartamento.setText("");
        txtEntrada.setText("");
        txtSalida.setText("");
        habilitarBoton();
    }//TODO -- limpiarCampos
     private boolean validarCampos() {
        if (txtNombres.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo nombres");
            return false;
        }else if(txtDepartamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo departamento");
            return false;
        }else if(txtEntrada.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo hora entrada");
            return false;
        }else if(txtSalida.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo hora salida");
            return false;
        }
        return  true;
    }//TODO -- validarCampos
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        clasesHospital.Horarios ch=new clasesHospital.Horarios();
        ch.editarHorarios(tblHorarios);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        boolean validar = validarCampos();
        if(validar == true){
            clasesHospital.Horarios ch = new clasesHospital.Horarios();
            ch.eliminarHorarios(tblHorarios, txtNombres);
            limpiarCampos();
            habilitarBoton();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSeleccionarMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarMedicamentosActionPerformed
        // TODO add your handling code here:
        clasesHospital.Horarios ch = new clasesHospital.Horarios();
        ch.seleccionarHorarios(tblHorarios);
        btnGuardar.setEnabled(false);
        txtNombres.setText(ch.getNombres());
        txtDepartamento.setText(ch.getDepartamento());
        txtEntrada.setText(ch.getEntrada());
        txtSalida.setText(ch.getSalida());
        jcbExtras.setEnabled(true);
        jcbExtras.setSelectedItem(ch.getExtras());
    }//GEN-LAST:event_btnSeleccionarMedicamentosActionPerformed

    private void btnMostrarMedicamentos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMedicamentos1ActionPerformed
        // TODO add your handling code here:
        clasesHospital.Horarios ch = new clasesHospital.Horarios();
        ch.mostrarHorarios(tblHorarios);
    }//GEN-LAST:event_btnMostrarMedicamentos1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarMedicamentos1;
    private javax.swing.JButton btnSeleccionarMedicamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbExtras;
    private javax.swing.JPanel jpnDatos;
    private javax.swing.JTable tblHorarios;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
}

        
