/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hospital;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class pnlMedicamentos extends javax.swing.JPanel {

    /**
     * Creates new form pnlPacientes
     */
    private ImageIcon imagen;
    private Icon icono;
    public pnlMedicamentos() {
        initComponents();
        btnGuardar.setEnabled(false);
       // pintarImagen(portada, "src/hospital/Imagenes/medicamentos.jpg");
    }
    public void habilitarBoton() {
        if (!txtCodigoMedicamento.getText().isEmpty()
              && !txtNombreMedicamento.getText().isEmpty()  
              && !txtFechaeMedicamento.getText().isEmpty()
              && !txtFechacMedicamento.getText().isEmpty()
              && !txtStockMedicamento.getText().isEmpty()) {
            btnGuardar.setEnabled(true);
        }else {
             btnGuardar.setEnabled(true);
        }
    }
    private void pintarImagen(JLabel lbl, String ruta) {
         this.imagen = new ImageIcon(ruta);
         this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                 lbl.getWidth(), 
                 lbl.getHeight(),
                 Image.SCALE_DEFAULT)
         );
         lbl.setIcon(this.icono);//convierte imagen en icono
         this.repaint();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreMedicamento = new javax.swing.JTextField();
        txtFechaeMedicamento = new javax.swing.JTextField();
        txtFechacMedicamento = new javax.swing.JTextField();
        txtStockMedicamento = new javax.swing.JTextField();
        txtCodigoMedicamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnMostrarMedicamentos1 = new javax.swing.JButton();
        btnSeleccionarMedicamentos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicamento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        portada = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha elaboración:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha caducidad:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Stock:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        txtNombreMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreMedicamento.setBorder(null);
        txtNombreMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMedicamentoActionPerformed(evt);
            }
        });
        txtNombreMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreMedicamentoKeyReleased(evt);
            }
        });
        jPanel2.add(txtNombreMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 90, 20));

        txtFechaeMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaeMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFechaeMedicamento.setBorder(null);
        txtFechaeMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaeMedicamentoActionPerformed(evt);
            }
        });
        txtFechaeMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaeMedicamentoKeyReleased(evt);
            }
        });
        jPanel2.add(txtFechaeMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 90, 20));

        txtFechacMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        txtFechacMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFechacMedicamento.setBorder(null);
        txtFechacMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechacMedicamentoKeyReleased(evt);
            }
        });
        jPanel2.add(txtFechacMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 90, 20));

        txtStockMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        txtStockMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtStockMedicamento.setBorder(null);
        txtStockMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockMedicamentoActionPerformed(evt);
            }
        });
        txtStockMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStockMedicamentoKeyReleased(evt);
            }
        });
        jPanel2.add(txtStockMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 90, 20));

        txtCodigoMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCodigoMedicamento.setBorder(null);
        txtCodigoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoMedicamentoActionPerformed(evt);
            }
        });
        txtCodigoMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoMedicamentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoMedicamentoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodigoMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 90, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Código:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 90, 10));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 90, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 90, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 90, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 90, 10));

        btnGuardar.setBackground(new java.awt.Color(0, 204, 153));
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 60, -1));

        btnMostrarMedicamentos1.setBackground(new java.awt.Color(0, 204, 153));
        btnMostrarMedicamentos1.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarMedicamentos1.setText("Mostrar");
        btnMostrarMedicamentos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrarMedicamentos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMedicamentos1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnMostrarMedicamentos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 50, 20));

        btnSeleccionarMedicamentos.setBackground(new java.awt.Color(0, 204, 153));
        btnSeleccionarMedicamentos.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionarMedicamentos.setText("Seleccionar");
        btnSeleccionarMedicamentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeleccionarMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarMedicamentosActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeleccionarMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 204, 153));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 60, -1));

        btnEditar.setBackground(new java.awt.Color(0, 204, 153));
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 60, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 270, 270));

        tblMedicamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombres", "Fecha Ela.", "Fecha. Cad.", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tblMedicamento);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 340, 270));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestionar Medicamentos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        portada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/medicamentos.jpg"))); // NOI18N
        add(portada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 250, 160));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/fondoMedi.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMedicamentoActionPerformed

    private void txtNombreMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreMedicamentoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtNombreMedicamentoKeyReleased

    private void txtFechaeMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaeMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaeMedicamentoActionPerformed

    private void txtFechaeMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaeMedicamentoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtFechaeMedicamentoKeyReleased

    private void txtFechacMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechacMedicamentoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtFechacMedicamentoKeyReleased

    private void txtStockMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockMedicamentoActionPerformed

    private void txtStockMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockMedicamentoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtStockMedicamentoKeyReleased

    private void txtCodigoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMedicamentoActionPerformed

    private void txtCodigoMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoMedicamentoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtCodigoMedicamentoKeyReleased

    private void txtCodigoMedicamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoMedicamentoKeyTyped
        // TODO add your handling code here:
        //se activa cuando se escribe
    }//GEN-LAST:event_txtCodigoMedicamentoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        boolean validar = validarCampos();
        if(validar == true){
            clasesHospital.Medicamentos cm = new clasesHospital.Medicamentos();
            cm.setCodigoMedicamento(txtCodigoMedicamento.getText());
            cm.setNombreMedicamento(txtNombreMedicamento.getText());
            cm.setFechaElaboracion(txtFechaeMedicamento.getText());
            cm.setFechaCaducidad(txtFechacMedicamento.getText());
            cm.setStockMedicamento(txtStockMedicamento.getText());
            cm.guardarMedicamento();
            limpiarCampos();
            btnGuardar.setEnabled(false);
            cm.mostrarMedicamentos(tblMedicamento);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

     private void limpiarCampos() {
        txtCodigoMedicamento.setText("");
        txtNombreMedicamento.setText("");
        txtFechaeMedicamento.setText("");
        txtFechacMedicamento.setText("");
        txtStockMedicamento.setText("");
    }//TODO -- limpiarCampos
     private boolean validarCampos() {
        if (txtCodigoMedicamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo código");
            return false;
        }else if(txtNombreMedicamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo nombre");
            return false;
        }else if(txtFechaeMedicamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo fecha elaboracion");
            return false;
        }else if(txtFechacMedicamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo fecha caducidad");
            return false;
        }else if(txtStockMedicamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo Stock");
            return false;
        }
        return  true;
    }//TODO -- validarCampos
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        clasesHospital.Medicamentos cm=new clasesHospital.Medicamentos();
        cm.editarMedicamento(tblMedicamento);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        boolean validar = validarCampos();
        if(validar == true){
            clasesHospital.Medicamentos cm=new clasesHospital.Medicamentos();
            cm.eliminarMedicamento(tblMedicamento, txtCodigoMedicamento);
            limpiarCampos();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSeleccionarMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarMedicamentosActionPerformed
        // TODO add your handling code here:
        clasesHospital.Medicamentos cm=new clasesHospital.Medicamentos();
        cm.seleccionarMedicamentos(tblMedicamento);
        txtCodigoMedicamento.setText(cm.getCodigoMedicamento());
        txtNombreMedicamento.setText(cm.getNombreMedicamento());
        txtFechaeMedicamento.setText(cm.getFechaElaboracion());
        txtFechacMedicamento.setText(cm.getFechaCaducidad());
        txtStockMedicamento.setText(cm.getStockMedicamento());
    }//GEN-LAST:event_btnSeleccionarMedicamentosActionPerformed

    private void btnMostrarMedicamentos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMedicamentos1ActionPerformed
        // TODO add your handling code here:
        clasesHospital.Medicamentos cm=new clasesHospital.Medicamentos();
        cm.mostrarMedicamentos(tblMedicamento);
    }//GEN-LAST:event_btnMostrarMedicamentos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarMedicamentos1;
    private javax.swing.JButton btnSeleccionarMedicamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel portada;
    private javax.swing.JTable tblMedicamento;
    private javax.swing.JTextField txtCodigoMedicamento;
    private javax.swing.JTextField txtFechacMedicamento;
    private javax.swing.JTextField txtFechaeMedicamento;
    private javax.swing.JTextField txtNombreMedicamento;
    private javax.swing.JTextField txtStockMedicamento;
    // End of variables declaration//GEN-END:variables
}
