/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hospital;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class pnlMedicamentos extends javax.swing.JPanel {

    /**
     * Creates new form pnlPacientes
     */
    
    public pnlMedicamentos() {
        initComponents();
        btnGuardar.setEnabled(false);
        jcbTipo.setEnabled(false);
    }
    public void habilitarBoton() {
        if (!txtCodigoMedicamento.getText().isEmpty()
              && !txtNombreMedicamento.getText().isEmpty()  
              && !txtFechaeMedicamento.getText().isEmpty()
              && !txtFechacMedicamento.getText().isEmpty()
              && !txtStockMedicamento.getText().isEmpty()) {
            jcbTipo.setEnabled(true);
            btnGuardar.setEnabled(true);
           
        }else {
            jcbTipo.setEnabled(false);
            btnGuardar.setEnabled(false);
             
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnDatos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreMedicamento = new javax.swing.JTextField();
        txtFechaeMedicamento = new javax.swing.JTextField();
        txtFechacMedicamento = new javax.swing.JTextField();
        txtStockMedicamento = new javax.swing.JTextField();
        txtCodigoMedicamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnMostrarMedicamentos1 = new javax.swing.JButton();
        btnSeleccionarMedicamentos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicamento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        portada = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnDatos.setBackground(new java.awt.Color(0, 153, 153));
        jpnDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jpnDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha elaboración:");
        jpnDatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha caducidad:");
        jpnDatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo:");
        jpnDatos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        txtNombreMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreMedicamento.setBorder(null);
        txtNombreMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMedicamentoActionPerformed(evt);
            }
        });
        txtNombreMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreMedicamentoKeyReleased(evt);
            }
        });
        jpnDatos.add(txtNombreMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 90, 30));

        txtFechaeMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaeMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFechaeMedicamento.setBorder(null);
        txtFechaeMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaeMedicamentoActionPerformed(evt);
            }
        });
        txtFechaeMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaeMedicamentoKeyReleased(evt);
            }
        });
        jpnDatos.add(txtFechaeMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 90, 30));

        txtFechacMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        txtFechacMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFechacMedicamento.setBorder(null);
        txtFechacMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechacMedicamentoKeyReleased(evt);
            }
        });
        jpnDatos.add(txtFechacMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 90, 30));

        txtStockMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        txtStockMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtStockMedicamento.setBorder(null);
        txtStockMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockMedicamentoActionPerformed(evt);
            }
        });
        txtStockMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStockMedicamentoKeyReleased(evt);
            }
        });
        jpnDatos.add(txtStockMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 90, -1));

        txtCodigoMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCodigoMedicamento.setBorder(null);
        txtCodigoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoMedicamentoActionPerformed(evt);
            }
        });
        txtCodigoMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoMedicamentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoMedicamentoKeyTyped(evt);
            }
        });
        jpnDatos.add(txtCodigoMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Código:");
        jpnDatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 204, 153));
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpnDatos.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 60, -1));

        btnMostrarMedicamentos1.setBackground(new java.awt.Color(0, 204, 153));
        btnMostrarMedicamentos1.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarMedicamentos1.setText("Mostrar");
        btnMostrarMedicamentos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrarMedicamentos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMedicamentos1ActionPerformed(evt);
            }
        });
        jpnDatos.add(btnMostrarMedicamentos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 60, 20));

        btnSeleccionarMedicamentos.setBackground(new java.awt.Color(0, 204, 153));
        btnSeleccionarMedicamentos.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionarMedicamentos.setText("Seleccionar");
        btnSeleccionarMedicamentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeleccionarMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarMedicamentosActionPerformed(evt);
            }
        });
        jpnDatos.add(btnSeleccionarMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 80, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 204, 153));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpnDatos.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 60, -1));

        btnEditar.setBackground(new java.awt.Color(0, 204, 153));
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jpnDatos.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Stock:");
        jpnDatos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "jarabe", "pastillas", "inyección", "Inalables" }));
        jpnDatos.add(jcbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 90, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/xs.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnDatos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 450));

        add(jpnDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 280, 450));

        tblMedicamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombres", "Fecha Ela.", "Fecha. Cad.", "Stock", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tblMedicamento);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 340, 270));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestionar Medicamentos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        portada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/medicamentos.jpg"))); // NOI18N
        add(portada, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 250, 160));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/fondoMedi.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMedicamentoActionPerformed

    private void txtNombreMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreMedicamentoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtNombreMedicamentoKeyReleased

    private void txtFechaeMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaeMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaeMedicamentoActionPerformed

    private void txtFechaeMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaeMedicamentoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtFechaeMedicamentoKeyReleased

    private void txtFechacMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechacMedicamentoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtFechacMedicamentoKeyReleased

    private void txtStockMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockMedicamentoActionPerformed

    private void txtStockMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockMedicamentoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtStockMedicamentoKeyReleased

    private void txtCodigoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMedicamentoActionPerformed

    private void txtCodigoMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoMedicamentoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtCodigoMedicamentoKeyReleased

    private void txtCodigoMedicamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoMedicamentoKeyTyped
        // TODO add your handling code here:
        //se activa cuando se escribe
    }//GEN-LAST:event_txtCodigoMedicamentoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        boolean validar = validarCampos();
        if(validar == true){
            clasesHospital.Medicamentos cm = new clasesHospital.Medicamentos();
            cm.setCodigoMedicamento(txtCodigoMedicamento.getText());
            cm.setNombreMedicamento(txtNombreMedicamento.getText());
            cm.setFechaElaboracion(txtFechaeMedicamento.getText());
            cm.setFechaCaducidad(txtFechacMedicamento.getText());
            cm.setStockMedicamento(txtStockMedicamento.getText());
            cm.setTipo(jcbTipo.getSelectedItem().toString());
            cm.guardarMedicamento();
            limpiarCampos();
            jcbTipo.setEnabled(false);
            btnGuardar.setEnabled(false);
            cm.mostrarMedicamentos(tblMedicamento);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

     private void limpiarCampos() {
        txtCodigoMedicamento.setText("");
        txtNombreMedicamento.setText("");
        txtFechaeMedicamento.setText("");
        txtFechacMedicamento.setText("");
        txtStockMedicamento.setText("");
    }//TODO -- limpiarCampos
     private boolean validarCampos() {
        if (txtCodigoMedicamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo código");
            return false;
        }else if(txtNombreMedicamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo nombre");
            return false;
        }else if(txtFechaeMedicamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo fecha elaboracion");
            return false;
        }else if(txtFechacMedicamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo fecha caducidad");
            return false;
        }else if(txtStockMedicamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo Stock");
            return false;
        }
        return  true;
    }//TODO -- validarCampos
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        clasesHospital.Medicamentos cm=new clasesHospital.Medicamentos();
        cm.editarMedicamento(tblMedicamento);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        boolean validar = validarCampos();
        if(validar == true){
            clasesHospital.Medicamentos cm=new clasesHospital.Medicamentos();
            cm.eliminarMedicamento(tblMedicamento, txtCodigoMedicamento);
            limpiarCampos();
            habilitarBoton();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSeleccionarMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarMedicamentosActionPerformed
        // TODO add your handling code here:
        clasesHospital.Medicamentos cm=new clasesHospital.Medicamentos();
        cm.seleccionarMedicamentos(tblMedicamento);
        btnGuardar.setEnabled(false);
        txtCodigoMedicamento.setText(cm.getCodigoMedicamento());
        txtNombreMedicamento.setText(cm.getNombreMedicamento());
        txtFechaeMedicamento.setText(cm.getFechaElaboracion());
        txtFechacMedicamento.setText(cm.getFechaCaducidad());
        txtStockMedicamento.setText(cm.getStockMedicamento());
        jcbTipo.setEnabled(true);
        jcbTipo.setSelectedItem(cm.getTipo());
    }//GEN-LAST:event_btnSeleccionarMedicamentosActionPerformed

    private void btnMostrarMedicamentos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMedicamentos1ActionPerformed
        // TODO add your handling code here:
        clasesHospital.Medicamentos cm=new clasesHospital.Medicamentos();
        cm.mostrarMedicamentos(tblMedicamento);
    }//GEN-LAST:event_btnMostrarMedicamentos1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarMedicamentos1;
    private javax.swing.JButton btnSeleccionarMedicamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JPanel jpnDatos;
    private javax.swing.JLabel portada;
    private javax.swing.JTable tblMedicamento;
    private javax.swing.JTextField txtCodigoMedicamento;
    private javax.swing.JTextField txtFechacMedicamento;
    private javax.swing.JTextField txtFechaeMedicamento;
    private javax.swing.JTextField txtNombreMedicamento;
    private javax.swing.JTextField txtStockMedicamento;
    // End of variables declaration//GEN-END:variables
}

        
