/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hospital;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class pnlVentas extends javax.swing.JPanel {

    /**
     * Creates new form pnlPacientes
     */
    public pnlVentas() {
        initComponents();
       
        jckJarabe.setEnabled(false);
        jckTableta.setEnabled(false); 
        jckInyectable.setEnabled(false);
        jckViaOral.setEnabled(false); 
        jdcFechaVenta.setEnabled(false);
        btnGuardar.setEnabled(false);
    }
    public void habilitarBoton() {
        if (!txtMedicamento.getText().isEmpty()
              && !txtCantidad.getText().isEmpty()  
              && !txtSubtotal.getText().isEmpty()
              && !txtRemitente.getText().isEmpty()
              && !txtCodigo.getText().isEmpty()  
              ) {
            jckJarabe.setEnabled(true);
            jckTableta.setEnabled(true);   
            jckInyectable.setEnabled(true);
            jckViaOral.setEnabled(true); 
            jdcFechaVenta.setEnabled(true);
            btnGuardar.setEnabled(true);
        }else {
            jckJarabe.setEnabled(false);
            jckJarabe.setSelected(false);
            jckTableta.setEnabled(false);
            jckTableta.setSelected(false);
            jckInyectable.setEnabled(false);
            jckInyectable.setSelected(false);
            jckViaOral.setEnabled(false); 
            jckViaOral.setSelected(false);
            jdcFechaVenta.setEnabled(false);
            btnGuardar.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTipoMedicamento = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtRemitente = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jckJarabe = new javax.swing.JCheckBox();
        jckTableta = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        jckInyectable = new javax.swing.JCheckBox();
        jckViaOral = new javax.swing.JCheckBox();
        jdcFechaVenta = new com.toedter.calendar.JDateChooser();
        txtTotal = new javax.swing.JTextField();
        jlbPanelx = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subtotal:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Codigo :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 80, -1));

        txtCantidad.setBackground(new java.awt.Color(204, 255, 204));
        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad.setBorder(null);
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
        });
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, 20));

        txtSubtotal.setBackground(new java.awt.Color(204, 255, 204));
        txtSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSubtotal.setBorder(null);
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        txtSubtotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubtotalKeyReleased(evt);
            }
        });
        jPanel2.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, 20));

        txtRemitente.setBackground(new java.awt.Color(204, 255, 204));
        txtRemitente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRemitente.setBorder(null);
        txtRemitente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRemitenteKeyReleased(evt);
            }
        });
        jPanel2.add(txtRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 160, 20));

        txtCodigo.setBackground(new java.awt.Color(204, 255, 204));
        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCodigo.setBorder(null);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 204, 153));
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, -1));

        btnMostrar.setBackground(new java.awt.Color(0, 204, 153));
        btnMostrar.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrar.setText("Mostrar");
        btnMostrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 50, 20));

        btnSeleccionar.setBackground(new java.awt.Color(0, 204, 153));
        btnSeleccionar.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 80, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 204, 153));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 60, -1));

        btnEditar.setBackground(new java.awt.Color(0, 204, 153));
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 60, -1));

        btngTipoMedicamento.add(jckJarabe);
        jckJarabe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jckJarabe.setForeground(new java.awt.Color(0, 0, 0));
        jckJarabe.setText("Jarabe");
        jckJarabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckJarabeActionPerformed(evt);
            }
        });
        jPanel2.add(jckJarabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        btngTipoMedicamento.add(jckTableta);
        jckTableta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jckTableta.setForeground(new java.awt.Color(0, 0, 0));
        jckTableta.setText("Tableta");
        jPanel2.add(jckTableta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Medicamento:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha venta:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Remitente:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 90, -1));

        txtMedicamento.setBackground(new java.awt.Color(204, 255, 204));
        txtMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMedicamento.setBorder(null);
        txtMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicamentoActionPerformed(evt);
            }
        });
        txtMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedicamentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedicamentoKeyTyped(evt);
            }
        });
        jPanel2.add(txtMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 160, 20));

        btngTipoMedicamento.add(jckInyectable);
        jckInyectable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jckInyectable.setForeground(new java.awt.Color(0, 0, 0));
        jckInyectable.setText("Inyectable");
        jPanel2.add(jckInyectable, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        btngTipoMedicamento.add(jckViaOral);
        jckViaOral.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jckViaOral.setForeground(new java.awt.Color(0, 0, 0));
        jckViaOral.setText("Via oral");
        jPanel2.add(jckViaOral, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jdcFechaVenta.setForeground(new java.awt.Color(204, 255, 204));
        jPanel2.add(jdcFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 130, -1));

        txtTotal.setBackground(new java.awt.Color(204, 255, 204));
        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTotal.setBorder(null);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 160, 20));

        jlbPanelx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/bbnnnn.jpg"))); // NOI18N
        jPanel2.add(jlbPanelx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 560));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 260));

        tblVentas.setBackground(new java.awt.Color(255, 153, 153));
        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Medicamento", "Cantidad", "Subtotal", "Remitente", "Codigo", "Tipo medicamento", "Fecha venta", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblVentas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 650, 210));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestionar Ventas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtSubtotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubtotalKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtSubtotalKeyReleased

    private void txtRemitenteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemitenteKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtRemitenteKeyReleased

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        //se activa cuando se escribe
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
         String fecha;
        SimpleDateFormat f = new SimpleDateFormat("yyyy/MM/dd");
        //pociciono en la variable
        fecha = f.format(jdcFechaVenta.getDate());
        boolean validar = validarCampos();
        if(validar == true){
            clasesHospital.Ventas cv = new clasesHospital.Ventas();
            cv.setMedicamento(txtMedicamento.getText());
            cv.setCantidad(txtCantidad.getText());
            cv.setSubtotal(txtSubtotal.getText());
            cv.setRemitente(txtRemitente.getText());
            cv.setTipo(validarSeleccion());
            cv.setFechaVenta(fecha);
            cv.setCodigo(txtCodigo.getText());
            cv.setTotal(txtTotal.getText());
            cv.guardarVentas();
            limpiarCampos();
            
            cv.mostrarVentas(tblVentas);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
   
    private String validarSeleccion() {
        String seleccion = "";
        if (jckJarabe.isSelected()) {
            seleccion = "Jarabe";
            return seleccion;
        }
        if (jckTableta.isSelected()) {
            seleccion = "Tableta";
            return seleccion;
        }
        if (jckInyectable.isSelected()) {
            seleccion = "Inyectable";
            return seleccion;
        }
        if (jckViaOral.isSelected()) {
            seleccion = "Via oral";
            return seleccion;
        }
        return seleccion;
    }
     private void limpiarCampos() {
        txtMedicamento.setText("");
        txtCantidad.setText("");
        txtSubtotal.setText("");
        txtRemitente.setText("");
        txtCodigo.setText("");
        txtTotal.setText("");
        btngTipoMedicamento.clearSelection();
        habilitarBoton();
    }//TODO -- limpiarCampos
     private boolean validarCampos() {
        if (txtMedicamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo cedula");
            return false;
        }else if(txtCantidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo nombre");
            return false;
        }else if(txtSubtotal.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo direccción");
            return false;
        }else if(txtRemitente.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo telefono");
            return false;
        }else if(txtCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo estado paciente");
            return false;
        }else if(txtTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete el campo estado paciente");
            return false;
        }
        return  true;
    }//TODO -- validarCampos
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        clasesHospital.Ventas cv=new clasesHospital.Ventas();
        cv.editarVenta(tblVentas);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        boolean validar = validarCampos();
        if(validar == true){
            clasesHospital.Ventas cv=new clasesHospital.Ventas();
            cv.eliminarVentas(tblVentas, txtCodigo);
            limpiarCampos();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        clasesHospital.Ventas cv=new clasesHospital.Ventas();
        cv.seleccionarVentas(tblVentas);
        txtMedicamento.setText(cv.getMedicamento());
        txtCantidad.setText(cv.getCantidad());
        txtSubtotal.setText(cv.getSubtotal());
        txtRemitente.setText(cv.getRemitente());
        txtCodigo.setText(cv.getCodigo());  
        txtTotal.setText(cv.getCodigo()); 
        habilitarBoton();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        clasesHospital.Ventas cv=new clasesHospital.Ventas();
        cv.mostrarVentas(tblVentas);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void jckJarabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckJarabeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jckJarabeActionPerformed

    private void txtMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicamentoActionPerformed

    private void txtMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicamentoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicamentoKeyReleased

    private void txtMedicamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicamentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicamentoKeyTyped

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyReleased

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.ButtonGroup btngTipoMedicamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jckInyectable;
    private javax.swing.JCheckBox jckJarabe;
    private javax.swing.JCheckBox jckTableta;
    private javax.swing.JCheckBox jckViaOral;
    private com.toedter.calendar.JDateChooser jdcFechaVenta;
    private javax.swing.JLabel jlbPanelx;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtRemitente;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
